/**
 * The built-in vault templates, embedded so `kmd init` scaffolds a working
 * vault offline. Filenames are the MCP server's resource contract
 * (wiki://template/{domain}/{kind} maps to them) — never rename.
 */
export const VAULT_TEMPLATES: Readonly<Record<string, string>> = {
  'note.md':
    '---\ntitle: {{title}}\ntags: []\ncreated: "{{timestamp}}"\nupdated: "{{timestamp}}"\n---\n\n# {{title}}\n',
  'project-adr.md':
    '---\ntitle: {{title}}\nkind: adr\nscope:\nstatus: active\nsummary:\ntags: []\nsupersedes:\nsuperseded_by:\nsources: []\ncreated: "{{timestamp}}"\nupdated: "{{timestamp}}"\n---\n\n# {{title}}\n\n## Status\n\n> [!info] Active\n\n## Context\n\nThe forces in tension — what made this a decision rather than an\nobvious step. Name the constraints; skip the history recap.\n\n## Decision\n\nWhat was decided, precisely. Predicates only — falsifiable, not\naspirational.\n\n## Rationale\n\nWhy this side won: which alternatives were live, and what killed each.\nAn ADR with no rejected alternative is a spec in disguise.\n\n## Consequences\n\nWhat this commits the project to going forward — including the costs\naccepted, not just the benefits claimed.\n\n## Links\n\n-\n',
  'project-index.md':
    '---\ntitle: {{title}}\nkind: project\nmethodology: sdd\nphase: 1\nrepo:\nscope:\nstatus: active\ntags: []\nsummary:\ncreated: "{{timestamp}}"\nupdated: "{{timestamp}}"\n---\n\n# {{title}}\n\n## Summary\n\nOne paragraph. What this project is and what it delivers.\n\n## Current Phase\n\nWhat\'s in flight right now. 1–3 sentences.\n\n## Links\n\n- [[projects/{{title}}/primer]]\n\n## Sources\n\n-\n',
  'project-intent.md':
    '---\ntitle: {{title}}\nkind: intent\nscope:\nstatus: draft\nsummary:\ntags: []\norigin: user\nsightings: 1\nsources: []\ncreated: "{{timestamp}}"\nupdated: "{{timestamp}}"\n---\n\n# {{title}}\n\n## Problem\n\nWhat cannot be done today, or what is broken, with the evidence.\n\n## Proposed outcome\n\nWhat better looks like, in one sentence.\n\n## Affected\n\nSurfaces, pages, code paths.\n\n## Constraints\n\n-\n\n## Open questions\n\n-\n\n## Falsification\n\nWhat a future session runs or reads to confirm or kill this.\n',
  'project-ops.md':
    '---\ntitle: {{title}}\nkind: ops\nscope:\nstatus: active\nsummary:\ntags: []\nsources: []\ncreated: "{{timestamp}}"\nupdated: "{{timestamp}}"\n---\n\n# {{title}}\n\n## Summary\n\nWhat this runbook operates and when it runs.\n\n## Context\n\nWhat triggers this flow; what breaks when it\'s skipped.\n\n## Details\n\nNumbered steps executable without asking: exact commands, expected\noutput, failure modes and their recovery. Predicates only — if a step\nneeds judgment, say whose.\n\n## Links\n\n-\n\n## Sources\n\n-\n',
  'project-plan.md':
    '---\ntitle: {{title}}\nkind: plan\nscope:\nstatus: active\nsummary:\ntags: []\ncreated: "{{timestamp}}"\nupdated: "{{timestamp}}"\n---\n\n# {{title}}\n\n## Goal\n\nOne sentence: what this phase delivers. If it needs two, it\'s two\nplans.\n\n## Scope\n\nWhat\'s in and — more important — what\'s out. Out-of-scope lines stop\nscope creep better than in-scope lines define it.\n\n## Milestones\n\nCheckable outcomes, not activities. Tick here; don\'t cascade ticks to\nindex.md unless phase or status changed.\n\n1.\n2.\n\n## Dependencies\n\n-\n',
  'project-primer.md':
    '---\ncreated: "{{timestamp}}"\nupdated: "{{timestamp}}"\n---\n\n# Primer\n\nThe reader is an agent: `prime` inlines this page into the next session\'s\ncontext. About 300 words across four sections, in the `signal-dense`\nregister, every term a canonical handle from `spec-context`. Nothing a\nquery or another surface derives: invariants live in the project\ninstructions, versions and release state in the changelog and tags, counts\nand active ADRs come from `prime`, work items from the Story Index and the\nintents. Rewritten once per session close by `/handoff`, from a retro newer\nthan this page.\n\n## Focus\n\nThree lines: what the scope is doing now and why.\n\n## Next\n\nThe top three, from the Story Index and the draft intents by sightings. A\nslice named where one is in progress.\n\n1.\n2.\n3.\n\n## Open\n\nPointers to intents only. A question without an intent is filed as one\nfirst.\n\n- [[intent-]] —\n\n## Read order\n\nThree links, one line each: `[[wikilink]] — why`.\n\n1.\n2.\n3.\n',
  'project-spec.md':
    '---\ntitle: {{title}}\nkind: spec\nscope:\nstatus: active\nsummary:\ntags: []\nsources: []\ncreated: "{{timestamp}}"\nupdated: "{{timestamp}}"\n---\n\n# {{title}}\n\n## Summary\n\nOne paragraph, in predicates — the system\'s current shape, not its\nhistory. If you\'re recording a *choice* between alternatives, stop:\nthat\'s an ADR.\n\n## Context\n\nThe question this spec answers and who asks it. One paragraph, no\nnarrative arc.\n\n## Details\n\nThe actual contract: inputs, outputs, invariants, failure modes. Use\nsubsections per concern. Present tense — the spec describes what IS\nand must match current code at every commit.\n\n## Links\n\n-\n\n## Sources\n\n-\n',
  'project-story.md':
    '---\ntitle: {{title}}\nkind: story\nscope:\nparent:\nstatus: active\ntriage_state: needs-triage\ncategory: enhancement\nblocked_by: []\ntags: []\nsources: []\ncreated: "{{timestamp}}"\nupdated: "{{timestamp}}"\n---\n\n# {{title}}\n\n## User Story\n\nAs a {{actor}}, I want {{capability}}, so that {{benefit}}.\n\n## Scenarios\n\nScenarios are the test specification — each becomes a failing test\nbefore implementation. Write observable outcomes, not implementation\nsteps.\n\n**Scenario: {{scenario name}}**\n- Given {{precondition}}\n- When {{action}}\n- Then {{expected outcome}}\n\n**Scenario: {{edge case name}}**\n- Given {{precondition}}\n- When {{action}}\n- Then {{expected outcome}}\n\n## Slices\n\nVertical tracer bullets: each slice ships signature + implementation +\ntests + wiring, independently committable. `AFK` = agent works alone;\n`HITL` = human in the loop.\n\n- [ ] **Slice 1** — {{description}} · `AFK` · [[spec-{{topic}}]]\n- [ ] **Slice 2** — {{description}} · `HITL` · [[adr-{{decision}}]]\n\n## References\n\n- [[spec-{{related-spec}}]]\n- [[adr-{{related-adr}}]]\n',
  'research-article.md':
    '---\ntitle: {{title}}\nkind: article\ntopic:\nstatus: active\nsummary:\ntags: []\nsources: []\ncreated: "{{timestamp}}"\nupdated: "{{timestamp}}"\n---\n\n# {{title}}\n\n## Summary\n\nOne paragraph. What this page covers and why it matters.\n\n## Context\n\nWhy this page exists. The problem or question it addresses.\n\n## Details\n\nThe actual content. Use subsections as needed.\n\n## Links\n\n-\n\n## Sources\n\n-\n',
  'research-index.md':
    '---\ntitle: {{title}}\nkind: topic\nstatus: active\nsummary:\nconfidence: medium\nsource_count: 0\ntags: []\ncreated: "{{timestamp}}"\nupdated: "{{timestamp}}"\n---\n\n# {{title}}\n\n## Summary\n\nOne paragraph. What this research topic covers.\n\n## Confidence\n\nWhy the confidence level is what it is. What would raise or lower it.\n\n## Pages\n\n-\n\n## Sources\n\n-\n',
  'research-src.md':
    '---\ntitle: {{title}}\nkind: src\ntopic:\nstatus: active\nsummary:\ntags: []\nsource_url:\ncreated: "{{timestamp}}"\nupdated: "{{timestamp}}"\n---\n\n# {{title}}\n\n## Summary\n\nWhat this source is. Author, origin, year.\n\n## Key Points\n\n-\n\n## Quotes\n\n>\n\n## Relevance\n\nWhy this source matters to the topic.\n\n## Citation\n\n`{author, year, title, url}`\n'
};
