/**
 * The built-in vault templates, embedded so `kmd init` scaffolds a working
 * vault offline. Filenames are the MCP server's resource contract
 * (wiki://template/{domain}/{kind} maps to them) — never rename.
 */
export const VAULT_TEMPLATES: Readonly<Record<string, string>> = {
  'note.md':
    '---\ntitle: {{title}}\ntags: []\ncreated: "{{date}}"\nupdated: {{date}}\n---\n\n# {{title}}\n',
  'project-adr.md':
    '---\ntitle: {{title}}\nkind: adr\nscope:\nstatus: active\nsummary:\ntags: []\nsupersedes:\nsuperseded_by:\nsources: []\ncreated: "{{date}}"\nupdated: {{date}}\n---\n\n# {{title}}\n\n## Status\n\n> [!info] Active\n\n## Context\n\nThe forces in tension — what made this a decision rather than an\nobvious step. Name the constraints; skip the history recap.\n\n## Decision\n\nWhat was decided, precisely. Predicates only — falsifiable, not\naspirational.\n\n## Rationale\n\nWhy this side won: which alternatives were live, and what killed each.\nAn ADR with no rejected alternative is a spec in disguise.\n\n## Consequences\n\nWhat this commits the project to going forward — including the costs\naccepted, not just the benefits claimed.\n\n## Links\n\n-\n',
  'project-index.md':
    '---\ntitle: {{title}}\nkind: project\nmethodology: sdd\nphase: 1\nrepo:\nscope:\nstatus: active\ntags: []\nsummary:\ncreated: "{{date}}"\nupdated: {{date}}\n---\n\n# {{title}}\n\n## Summary\n\nOne paragraph. What this project is and what it delivers.\n\n## Current Phase\n\nWhat\'s in flight right now. 1–3 sentences.\n\n## Links\n\n- [[projects/{{title}}/primer]]\n\n## Sources\n\n-\n',
  'project-ops.md':
    '---\ntitle: {{title}}\nkind: ops\nscope:\nstatus: active\nsummary:\ntags: []\nsources: []\ncreated: "{{date}}"\nupdated: {{date}}\n---\n\n# {{title}}\n\n## Summary\n\nWhat this runbook operates and when it runs.\n\n## Context\n\nWhat triggers this flow; what breaks when it\'s skipped.\n\n## Details\n\nNumbered steps executable without asking: exact commands, expected\noutput, failure modes and their recovery. Predicates only — if a step\nneeds judgment, say whose.\n\n## Links\n\n-\n\n## Sources\n\n-\n',
  'project-plan.md':
    "---\ntitle: {{title}}\nkind: plan\nscope:\nstatus: active\nsummary:\ntags: []\ncreated: \"{{date}}\"\nupdated: {{date}}\n---\n\n# {{title}}\n\n## Goal\n\nOne sentence: what this phase delivers. If it needs two, it's two\nplans.\n\n## Scope\n\nWhat's in and — more important — what's out. Out-of-scope lines stop\nscope creep better than in-scope lines define it.\n\n## Milestones\n\nCheckable outcomes, not activities. Tick here; don't cascade ticks to\nindex.md unless phase or status changed.\n\n1.\n2.\n\n## Dependencies\n\n-\n\n## Status Log\n\nDated one-liners, newest first. This is the only history surface —\nprimer and index stay clean.\n\n- {{date}}: Phase started.\n",
  'project-primer.md':
    '---\ncreated: "{{date}}"\nupdated: {{date}}\n---\n\n# Primer\n\n## Current Focus\n\nWhat we\'re working on right now. 1–3 sentences. Not a history log —\nprogress lives in plan checkboxes; history lives in git.\n\n## Open Questions\n\nCurrently-open questions only. Strip on resolution; reflect the\nresolution in the relevant ADR or spec, not here.\n\n-\n\n## Blocked On\n\nNothing currently. List only items genuinely blocking forward\nprogress.\n\n## Load-bearing invariants (optional)\n\nFacts not derivable from code or commits — pipeline orderings, sync\nconstraints, file-location rationales. The kind of fact a fresh-context\nagent would otherwise re-derive incorrectly. Durable across sessions.\n\n## Read Order (optional)\n\n≤5 entries. Wiki/doc pointers — what to read to orient. Each entry\none line: `[[wikilink]] — why`.\n\n1.\n\n## Working set (optional)\n\n≤10 entries. File pointers (code, fixtures, configs) for the\nimmediate Next Steps, with one-line context. Lets a fresh-context\nagent skip the discovery loop. Task-scoped — refresh when focus\nshifts. Most valuable when transitioning phases or starting a new\nfeature; can be skipped mid-slice when the immediate context already\ncarries it.\n\n- `path/to/file` — why it\'s relevant for the next steps.\n',
  'project-spec.md':
    "---\ntitle: {{title}}\nkind: spec\nscope:\nstatus: active\nsummary:\ntags: []\nsources: []\ncreated: \"{{date}}\"\nupdated: {{date}}\n---\n\n# {{title}}\n\n## Summary\n\nOne paragraph, in predicates — the system's current shape, not its\nhistory. If you're recording a *choice* between alternatives, stop:\nthat's an ADR.\n\n## Context\n\nThe question this spec answers and who asks it. One paragraph, no\nnarrative arc.\n\n## Details\n\nThe actual contract: inputs, outputs, invariants, failure modes. Use\nsubsections per concern. Present tense — the spec describes what IS\nand must match current code at every commit.\n\n## Links\n\n-\n\n## Sources\n\n-\n",
  'project-story.md':
    '---\ntitle: {{title}}\nkind: story\nscope:\nparent:\nstatus: active\ntriage_state: needs-triage\ncategory: enhancement\nblocked_by: []\ntags: []\nsources: []\ncreated: "{{date}}"\nupdated: {{date}}\n---\n\n# {{title}}\n\n## User Story\n\nAs a {{actor}}, I want {{capability}}, so that {{benefit}}.\n\n## Scenarios\n\nScenarios are the test specification — each becomes a failing test\nbefore implementation. Write observable outcomes, not implementation\nsteps.\n\n**Scenario: {{scenario name}}**\n- Given {{precondition}}\n- When {{action}}\n- Then {{expected outcome}}\n\n**Scenario: {{edge case name}}**\n- Given {{precondition}}\n- When {{action}}\n- Then {{expected outcome}}\n\n## Slices\n\nVertical tracer bullets: each slice ships signature + implementation +\ntests + wiring, independently committable. `AFK` = agent works alone;\n`HITL` = human in the loop.\n\n- [ ] **Slice 1** — {{description}} · `AFK` · [[spec-{{topic}}]]\n- [ ] **Slice 2** — {{description}} · `HITL` · [[adr-{{decision}}]]\n\n## References\n\n- [[spec-{{related-spec}}]]\n- [[adr-{{related-adr}}]]\n',
  'research-article.md':
    '---\ntitle: {{title}}\nkind: article\ntopic:\nstatus: active\nsummary:\ntags: []\nsources: []\ncreated: "{{date}}"\nupdated: {{date}}\n---\n\n# {{title}}\n\n## Summary\n\nOne paragraph. What this page covers and why it matters.\n\n## Context\n\nWhy this page exists. The problem or question it addresses.\n\n## Details\n\nThe actual content. Use subsections as needed.\n\n## Links\n\n-\n\n## Sources\n\n-\n',
  'research-index.md':
    '---\ntitle: {{title}}\nkind: topic\nstatus: active\nsummary:\nconfidence: medium\nsource_count: 0\ntags: []\ncreated: "{{date}}"\nupdated: {{date}}\n---\n\n# {{title}}\n\n## Summary\n\nOne paragraph. What this research topic covers.\n\n## Confidence\n\nWhy the confidence level is what it is. What would raise or lower it.\n\n## Pages\n\n-\n\n## Sources\n\n-\n',
  'research-src.md':
    '---\ntitle: {{title}}\nkind: src\ntopic:\nstatus: active\nsummary:\ntags: []\nsource_url:\ncreated: "{{date}}"\nupdated: {{date}}\n---\n\n# {{title}}\n\n## Summary\n\nWhat this source is. Author, origin, year.\n\n## Key Points\n\n-\n\n## Quotes\n\n>\n\n## Relevance\n\nWhy this source matters to the topic.\n\n## Citation\n\n`{author, year, title, url}`\n'
};
